version = 0.1

[default.deploy.parameters]
stack_name = "piano-mc-update-paid-subscribers"
resolve_s3 = true
s3_prefix = "piano-mc-update-paid-subscribers"
profile = "fsn"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SecretId=\"piano-mailchimp-webhook/production\" SecretRegion=\"eu-west-1\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
